"""MemoryServiceProtocol — structural interface for mcp-memory-service.

Defined here so it can be imported anywhere without pulling in the optional
mcp_memory_service package at module load time.
"""

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MemoryServiceProtocol(Protocol):
    """Structural interface for mcp-memory-service MemoryService."""

    async def store_memory(self, content: str, **kwargs: Any) -> dict[str, Any]: ...
    async def retrieve_memories(self, query: str, **kwargs: Any) -> dict[str, Any]: ...
    async def search_by_tag(self, tags: Any, **kwargs: Any) -> dict[str, Any]: ...
    async def list_memories(self, **kwargs: Any) -> dict[str, Any]: ...
    async def delete_memory(self, content_hash: str) -> dict[str, Any]: ...
    async def health_check(self) -> dict[str, Any]: ...
    async def close(self) -> None: ...
